import Link from "next/link";
import { ArrowUpRight, Crown, Medal, Trophy } from "lucide-react";

const entries = [
  { rank: 1, name: "Maya Chen", handle: "mayacodes", solved: 184, points: "9,420", tone: "text-amber-300" },
  { rank: 2, name: "Arjun Rao", handle: "arjun.dev", solved: 171, points: "8,870", tone: "text-slate-300" },
  { rank: 3, name: "Noah Williams", handle: "nwilliams", solved: 159, points: "8,210", tone: "text-orange-300" },
  { rank: 4, name: "You", handle: "Sign in to join", solved: 0, points: "—", tone: "text-indigo-300" },
];

export default function LeaderboardPage() {
  return <main className="mx-auto max-w-5xl px-4 py-12 sm:px-6"><div className="mb-9 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow mb-3">The arena</p><h1 className="text-3xl font-bold text-white">Leaderboard</h1><p className="mt-2 text-slate-400">Consistency compounds. See who is solving with intent.</p></div><div className="rounded-xl border border-white/10 bg-white/[0.03] px-4 py-3 text-right"><p className="text-xs text-slate-500">Season 01</p><p className="font-semibold text-white">September sprint</p></div></div><div className="grid gap-4 sm:grid-cols-3"><div className="card p-5"><Crown className="mb-8 h-5 w-5 text-amber-300" /><p className="text-2xl font-bold text-white">12.8k</p><p className="mt-1 text-xs text-slate-500">points earned</p></div><div className="card p-5"><Trophy className="mb-8 h-5 w-5 text-indigo-300" /><p className="text-2xl font-bold text-white">184</p><p className="mt-1 text-xs text-slate-500">top solver streak</p></div><div className="card p-5"><Medal className="mb-8 h-5 w-5 text-emerald-300" /><p className="text-2xl font-bold text-white">2,410</p><p className="mt-1 text-xs text-slate-500">active competitors</p></div></div><div className="card mt-5 overflow-hidden"><div className="grid grid-cols-[3rem_1fr_5rem_6rem] gap-3 border-b border-white/10 px-5 py-3 text-[11px] font-bold uppercase tracking-wider text-slate-600"><span>#</span><span>Competitor</span><span className="text-right">Solved</span><span className="text-right">Points</span></div>{entries.map((entry) => <div key={entry.rank} className={`grid grid-cols-[3rem_1fr_5rem_6rem] items-center gap-3 border-b border-white/5 px-5 py-4 last:border-0 ${entry.name === "You" ? "bg-indigo-400/[0.06]" : ""}`}><span className={`font-mono text-sm font-bold ${entry.tone}`}>{String(entry.rank).padStart(2, "0")}</span><div><p className="font-semibold text-white">{entry.name}</p><p className="text-xs text-slate-500">{entry.handle}</p></div><span className="text-right text-sm text-slate-300">{entry.solved}</span><span className="text-right font-mono text-sm text-indigo-200">{entry.points}</span></div>)}</div><div className="mt-6 text-center text-sm text-slate-500">Want your name on the board? <Link href="/signup" className="inline-flex items-center gap-1 text-indigo-300 hover:text-white">Create an account <ArrowUpRight className="h-4 w-4" /></Link></div></main>;
}